name: Run Android Test Github

on:
push:
    branches:
      - main


jobs:
  run-mobile-tests:
    runs-on: macos-latest

    steps:
      - name: setup java
        uses: action/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: pull the project in to the runner
        uses: actions/checkout@v3

      - name: setup appium
        run: |
          npm install -g appium@v8.4.0
          start /B cmd /C "appium.cmd >NUL 2>NUL"

      - name: run appium android
        uses: reactivecircus/android-emulator-runner@v2
        with:
           api-level: 29
           script: mvn test -Pandroid